server:
  port: 8764

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

zuul:
  #Service will be mapped under the /api URI
  prefix: /api
#  Uncomment to disable auto-registering all services read from Eureka
#  ignoredServices: '*'
  routes:
    Maintanance-Services:
      path: /redirect/**
      url: http://localhost:8763
    db-service:
      path: /**
      url: http://localhost:8300
 
spring:
  application:
    name: zuul-server